disabled_rules:
    - nesting
    - file_length

excluded:
    - .build

switch_case_alignment:
    indented_cases: true
    
# Some code has been manually converted from the RFC and uses single-character identifiers.
identifier_name:
    min_length: 1
