disabled_rules:
    - nesting

switch_case_alignment:
    indented_cases: true
    
# Some code has been manually converted from the RFC and uses single-character identifiers.
identifier_name:
    min_length: 1
