name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
